// GENERATED FILE. Run npm run generate:approval-policy-registry.
// Source: schemas/approval-policy-registry.json

export const APPROVAL_POLICY_REGISTRY = Object.freeze({
  "versions": [
    1,
    2
  ],
  "latest_version": 2,
  "effects": [
    "allow",
    "deny",
    "ask"
  ],
  "actions": [
    "agent.plan.continue",
    "agent.input.answer",
    "agent.form.submit",
    "agent.url.open",
    "secret.input",
    "fs.read",
    "fs.list",
    "fs.search",
    "fs.create",
    "fs.write",
    "fs.append",
    "fs.patch",
    "fs.copy",
    "fs.move",
    "fs.delete",
    "fs.permissions.write",
    "fs.unknown",
    "process.exec",
    "process.opaque",
    "process.signal",
    "shell.dynamic",
    "code.python.execute",
    "code.javascript.execute",
    "code.shell.execute",
    "code.opaque",
    "network.dns.resolve",
    "network.connect",
    "network.listen",
    "network.http.read",
    "network.http.write",
    "network.transfer.upload",
    "network.transfer.download",
    "vcs.read",
    "vcs.write",
    "vcs.destructive",
    "vcs.remote.read",
    "vcs.remote.write",
    "package.read",
    "package.install",
    "package.remove",
    "package.publish",
    "db.read",
    "db.insert",
    "db.update",
    "db.delete",
    "db.schema.create",
    "db.schema.alter",
    "db.schema.drop",
    "db.transaction",
    "db.admin",
    "db.unknown",
    "system.service.read",
    "system.service.manage",
    "system.identity.manage",
    "system.schedule.manage",
    "system.storage.manage",
    "infra.read",
    "infra.write",
    "infra.destroy",
    "permission.additional",
    "tool.unknown"
  ],
  "operators": [
    "exists",
    "not_exists",
    "eq",
    "neq",
    "glob",
    "not_glob",
    "contains",
    "not_contains",
    "starts_with",
    "ends_with",
    "path_under",
    "path_equals",
    "in",
    "not_in",
    "intersects",
    "contains_all",
    "lt",
    "lte",
    "gt",
    "gte",
    "between"
  ],
  "condition_fields": [
    "action",
    "risk",
    "confidence",
    "provider",
    "runtime",
    "interaction.kind",
    "interaction.source",
    "tool.name",
    "command.raw",
    "command.executable",
    "command.argv",
    "command.cwd",
    "command.dynamic",
    "command.segment",
    "resource.kind",
    "resource.path",
    "resource.uri",
    "network.protocol",
    "network.host",
    "network.port",
    "network.method",
    "database.engine",
    "database.operation",
    "database.database",
    "database.schema",
    "database.tables",
    "code.language",
    "code.script",
    "code.module",
    "code.sha256",
    "declaration.id"
  ],
  "limits": {
    "max_rules": 256,
    "max_declarations": 128,
    "max_condition_depth": 16,
    "max_condition_nodes": 1024
  },
  "path_canonicalization": "realpath-nearest-existing-ancestor",
  "unknown_operations": "ask"
});
