// Cross-language trust-evaluation vectors.
//
// The directory cache's trust decision is implemented twice — here and in
// `lib/features/security/device_e2ee_directory_cache.dart` — and the two have
// to agree, because a device that one side trusts and the other rejects is a
// device whose relayed messages fail with no error anywhere. The envelope and
// directory-head vectors cover the crypto; these cover the policy, which is
// where the implementations actually differed.
//
// `tests/deviceE2eeCrossLanguage.test.js` has the Dart counterpart and reads
// the same fixture.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { storeDeviceE2eeDirectoryCache } from "../src/security/deviceE2eeDirectoryCache.js";

const vectors = JSON.parse(readFileSync(
  new URL("./fixtures/device_e2ee_trust_vectors.json", import.meta.url),
  "utf8",
));

// The fixture is generated by `scripts/generate-device-e2ee-trust-fixtures.mjs`
// and copied into the App repository at
// `test/fixtures/device_e2ee_trust_vectors.json`, which has a mirror of this
// list. The two implementations only keep agreeing while they run the same set
// of cases, so this list is the tripwire: regenerating here without updating
// both copies fails both sides rather than quietly leaving one of them testing
// fewer inputs than the other.
const expectedCases = [
  "grandfathered_roots_accepted",
  "policy_signer_revoked_after_signing",
  "policy_signer_revoked_before_signing",
  "policy_signer_approved_after_signing",
  "policy_signature_forged",
  "admission_signed_inside_rotation_window",
  "policy_signer_rotated_after_signing",
  "admission_signed_after_rotation",
  "admitted_by_revoked_grandfathered_root",
  "admitted_by_live_grandfathered_root",
  "grandfathered_key_anchors_rotated_device",
  "reapproved_grandfathered_root",
  "one_revoked_root_among_live_ones",
  "grandfathered_key_absent_from_directory",
  "pending_device_alongside_live_roots",
  "policy_disabled_needs_no_proof",
  "policy_reset_to_unsigned",
  "admitted_by_app_that_then_rotated",
  "admitted_then_approver_removed",
  "chain_two_levels_accepted",
  "chain_two_levels_middle_removed",
  "cascade_recovers_by_reapproval",
];

assert.deepEqual(
  vectors.cases.map((vector) => vector.name),
  expectedCases,
  "the fixture no longer matches the shared vector list; copy it to the App "
    + "repository and update both copies of this list",
);

for (const vector of vectors.cases) {
  const accepted = (() => {
    try {
      storeDeviceE2eeDirectoryCache(
        join(mkdtempSync(join(tmpdir(), "originrouter-trust-vector-")), "cache"),
        vector.directory,
      );
      return true;
    } catch {
      return false;
    }
  })();
  assert.equal(
    accepted,
    vector.expect === "accept",
    `${vector.name}: expected ${vector.expect}. ${vector.why}`,
  );
}

console.log(`E2EE trust vectors ok (${vectors.cases.length} cases)`);
